services:
  postgres:
    image: postgres:15
    container_name: kvmp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kvmp_db
    ports:
      - "5432:5432"
    volumes:
      - kvmp_db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: kvm-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  kvmp_db:
  redisdata: